# Generated by Django 5.0.3 on 2024-03-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ProductName', max_length=50, verbose_name='Название')),
                ('price', models.IntegerField(default=1000, verbose_name='Цена')),
                ('firstDop', models.CharField(default='√ Качественно и быстро', max_length=30, verbose_name='Первый плюс')),
                ('secondDop', models.CharField(default='√ Качественно и быстро', max_length=30, verbose_name='Второй плюс')),
                ('thirdDop', models.CharField(default='√ Качественно и быстро', max_length=30, verbose_name='Третий плюс')),
                ('fourdDop', models.CharField(default='√ Качественно и быстро', max_length=30, verbose_name='Четвертый плюс')),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
