# Generated by Django 5.0.3 on 2024-03-31 12:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='relise',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Релиз'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='typepor',
            field=models.CharField(default='Program', max_length=50, verbose_name='Тип'),
        ),
    ]
